seed: 42
n_poly: 4
l_poly: [40, 40, 50, 50]
n_breaks: 24
persistence_length: 10.
blender: True
density: 0.01
notice_level: 3

# fire
dt_fire: 0.0005
force_fire: False
n_fire_blocks: 120
n_fire_steps: 1000

# run
n_run_blocks: 2000
n_run_steps: 2000
run_dump_period: 100
dt_langevin: 0.001

# rtm
rtm_prob: 0.25
rtm_magnitude: 7.5
rtm_period: 1000
