seed: 1999
n_poly: 4
l_poly: [24, 24, 36, 36]
n_breaks: 4
persistence_length: 30
rtm_prob: 0.25
rtm_magnitude: 3
sigma: 1.0
blender: True
density: 0.01
notice_level: 3
force_fire: True
n_fire_blocks: 50
n_fire_steps: 1000

n_run_blocks: 10000
n_run_steps: 100
dt_langevin: 0.001
dt_fire: 0.0005

