name: polychrom-hoomd
channels:
    - conda-forge
dependencies:
    - pip
    - python
    - numpy
    - scipy
    - matplotlib
    - pandas
    - hoomd=*gpu*
    - fresnel
    - gsd
    - joblib
    - pyside2
    - ipython
    - notebook
    - jupyter
    - pyyaml
    - requests
    - pip:
          -bpy
          - git+https://github.com/open2c/polykit.git
          - git+https://github.com/open2c/cooltools.git
          - git+https://github.com/mtortora/lattice-translocators.git
          - git+https://github.com/open2c/polychrom-hoomd.git


